language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y libmagickcore-dev libsdl-dev g++-4.9 && export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install imagemagick boost sdl; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DVERBOSE=5 -DSAMPLECODE=on ..

script: make

os:
  - linux
  - osx

osx_image: xcode61