language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libmagickcore-dev libboost-all-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install imagemagick boost; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DVERBOSE=5 -DSAMPLECODE=on ..

script: make

os:
  - linux
  - osx

osx_image: xcode61